fix(i18n): #RBS-141 Fix rbs i18n
OPEN-ENT-NG/rbs pull request #28
Opened 2022-08-02 13:15 UTC by AyaNADINI

## Describe your changes
In order to ensure that our module can be delivered in both languages French and English,
We skim through the template folder and replace in html files what is hard-written (manually written) with i18n tags while implementing the i18n file 

## Checklist tests
First, we create a ressource and we make a reservations in rbs.
We should have something like this : **Réservation validée**

 
## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-02 15:05 UTC, alicedraillard requested changes

2022-08-02 15:05 UTC, alicedraillard commented on src/main/resources/i18n/fr.json
> +  "rbs.calendar.item.validated": "Réservation validée",
combine les i18n de "Réservation" et "validée" plutot dans le html

2022-08-02 15:05 UTC, alicedraillard commented on deployment/rbs/conf.json.template
> +      "name": "net.atos~rbs~1.13-SNAPSHOT",
MAJ ta branche

2022-08-02 16:01 UTC, JinDouang commented
tu as fait des TU ?

2022-08-03 07:30 UTC, AyaNADINI commented
> tu as fait des TU ?
@JinDouang non mais Bastien avait dit l'autre fois que la première coche ne veux pas dire que tu a dit comment tester ton code fonctionnellement ? Genre
Aller sur la page d'accueil
Le bouton appart en haut a droite

2022-08-03 07:56 UTC, AyaNADINI commented on src/main/resources/i18n/fr.json
> +  "rbs.calendar.item.validated": "Réservation validée",
Bien entendu, j'ai corrigé

2022-08-03 09:08 UTC, JinDouang commented
> 
 I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in Checklist tests)

2022-08-03 12:55 UTC, alicedraillard requested changes

2022-08-03 12:55 UTC, alicedraillard commented on src/main/resources/public/template/calendar/tooltip-template.html
> +            <span class="green-text"><i18n>rbs.booking.details.header.validated.one</i18n></span>
<i18n>rbs.errors.objects.booking</i18n> <i18n>rbs.booking.details.header.validated.one</i18n>

2022-08-03 12:55 UTC, alicedraillard commented on src/main/resources/public/template/calendar/tooltip-template.html
> +            <span class="orange-text"><i18n>rbs.boooking.status.awaiting.validation.lowercase</i18n></span>
rbs.boooking.status.awaiting.validation (attention le i18n que tu avais mis n'a pas de majuscule)

2022-08-03 12:55 UTC, alicedraillard commented on src/main/resources/public/template/calendar/tooltip-template.html
> +            <span class="red-text"><i18n>rbs.booking.details.header.refused.one</i18n></span>
idem que précédemment + il faut trouver un "refusée" pas "refusé"

2022-08-03 12:55 UTC, alicedraillard commented on src/main/resources/public/template/calendar/tooltip-template.html
> +            <span class="yellow-text"><i18n>rbs.booking.status.suspended</i18n></span>
idem + rbs.booking.status.suspended.lowercase (cette fois il ne fallait pas de majuscule)

2022-08-03 12:55 UTC, alicedraillard commented on src/main/resources/public/template/calendar/tooltip-template.html
> +        <p class="quantity"><i18n>rbs.booking.details.quantity</i18n> [[formatTextTooltipQuantity(item)]]</p>
rajouter le hash pour :

2022-08-03 12:55 UTC, alicedraillard commented on src/main/resources/i18n/fr.json
> +  "rbs.calendar.item.owner": "Par"
rbs.by

2022-08-03 12:56 UTC, flmartineau approved these changes

2022-08-03 15:54 UTC, qpic-cgi commented on src/main/resources/i18n/en.json
> +    "rbs.booking.details.quantity": "Quantité :",
Utilise les html entities directement dans ton html plutôt

2022-08-03 15:54 UTC, qpic-cgi commented on src/main/resources/i18n/fr.json
> +  "rbs.booking.details.quantity": "Quantité :",
Utilise les html entities directement dans ton html plutôt

2022-08-04 07:45 UTC, AyaNADINI commented on src/main/resources/i18n/en.json
> +    "rbs.booking.details.quantity": "Quantité :",
D'accord, merciii

2022-08-04 08:33 UTC, alicedraillard commented on src/main/resources/public/template/calendar/tooltip-template.html
> +            <span class="orange-text"><i18n>rbs.booking.status.awaiting.validation</i18n></span>
cet i18n n'exist pas ??

2022-08-04 08:36 UTC, BastienBenard approved these changes

2022-08-04 08:40 UTC, AyaNADINI commented on src/main/resources/public/template/calendar/tooltip-template.html
> +            <span class="orange-text"><i18n>rbs.booking.status.awaiting.validation</i18n></span>
rbs.boooking.status.awaiting.validation c'est avec un triple o, je l'avais corrigé sur les i18n mais j'ai pas fait le push

2022-08-04 08:42 UTC, alicedraillard commented on src/main/resources/public/template/calendar/tooltip-template.html
>              <p>[[getPeriodicSummary(item)]]</p>
tu es sûre que c'est le seul fichier où il manque des i18n ?

2022-08-04 08:47 UTC, AyaNADINI commented on src/main/resources/public/template/calendar/tooltip-template.html
>              <p>[[getPeriodicSummary(item)]]</p>
on touche pas a ce qui est entre [[ ]], c'est ce que j'ai compris

2022-08-04 08:50 UTC, alicedraillard commented on src/main/resources/public/template/calendar/tooltip-template.html
>              <p>[[getPeriodicSummary(item)]]</p>
non mais dans d'autres fichiers HTML

2022-08-04 08:51 UTC, AyaNADINI commented on src/main/resources/public/template/calendar/tooltip-template.html
>              <p>[[getPeriodicSummary(item)]]</p>
non j'avais parcouru tous les fichiers mais je vais revérifier

2022-08-04 09:40 UTC, qpic-cgi approved these changes

2022-08-04 12:32 UTC, alicedraillard requested changes

2022-08-04 12:32 UTC, alicedraillard commented on src/main/resources/public/template/calendar/tooltip-template.html
>              <p>[[getPeriodicSummary(item)]]</p>
https://github.com/OPEN-ENT-NG/rbs/blob/dev/src/main/resources/public/template/resource/confirm-quantity-resource.html

2022-08-04 13:48 UTC, alicedraillard requested changes

2022-08-04 13:48 UTC, alicedraillard commented on src/main/resources/i18n/en.json
> +    "rbs.uppercase": "RBS",
rbs.title.uppercase

2022-08-04 13:48 UTC, alicedraillard commented on src/main/resources/view-src/admin.html
> +    <h1><i18n>rbs.uppercase</i18n></h1>
{{#i18n}}rbs.uppercase{{/i18n}}
(c'est un cas spécial)

2022-08-04 13:48 UTC, alicedraillard commented on src/main/resources/i18n/fr.json
> +  "rbs.booking.save": "Les gestionnaires devront définir les réservations à conserver.",
rbs.booking.manager.decision

2022-08-04 13:53 UTC, AyaNADINI commented on src/main/resources/i18n/fr.json
> +  "rbs.booking.save": "Les gestionnaires devront définir les réservations à conserver.",
pour les 2 dernières?

2022-08-04 14:15 UTC, merged

2022-08-04 14:28 UTC, AyaNADINI commented
Continue in https://github.com/OPEN-ENT-NG/rbs/compare/dev...RBS-141